export type Data = Record<string, string | number | boolean>;
export type CareRecord = {id:string;kind:string;data:Data;revision:number;created_at:string;updated_at:string;patient_id?:string;supplier_id?:string};
export type Field = {key:string;label:string;type?:'text'|'email'|'number'|'date'|'datetime-local'|'textarea'|'select'|'boolean';required?:boolean;options?:string[];ref?:string;min?:number;max?:number;hint?:string};
export type Module = {title:string;singular:string;description:string;group:string;fields:Field[];columns:string[];status?:string[]};
const patient:Field={key:'patientId',label:'Patient',ref:'patients',required:true};
const note:Field={key:'notes',label:'Notes',type:'textarea'};
const status=(options:string[]):Field=>({key:'status',label:'Status',type:'select',options,required:true});
export const modules:Record<string,Module>={
 patients:{title:'Patients',singular:'patient',description:'Every person, their devices and their care in one place.',group:'CARE',columns:['name','funding','planId','communication','status'],status:['Active','Review due','Inactive'],fields:[{key:'name',label:'Full name',required:true},{key:'email',label:'Email',type:'email'},{key:'phone',label:'Phone'},{key:'dateOfBirth',label:'Date of birth',type:'date'},{key:'postcode',label:'Postcode'},{key:'funding',label:'Funding',type:'select',options:['Private','NHS','Employer','Other'],required:true},{key:'planId',label:'Service plan',ref:'plans'},{key:'careHomeId',label:'Care home',ref:'care-homes'},{key:'communication',label:'Preferred contact',type:'select',options:['Email','Telephone','Text','Carer']},{key:'nextReview',label:'Next review',type:'date'},status(['Active','Review due','Inactive']),note]},
 devices:{title:'Device passports',singular:'device',description:'Device identity, warranty and servicing history.',group:'CARE',columns:['name','patientId','serial','side','warranty','status'],status:['In use','In repair','Loan','Retired'],fields:[patient,{key:'name',label:'Device model',required:true},{key:'manufacturer',label:'Manufacturer',required:true},{key:'serial',label:'Serial number',required:true},{key:'side',label:'Ear',type:'select',options:['Left','Right','Pair'],required:true},{key:'fitted',label:'Fitted on',type:'date'},{key:'warranty',label:'Warranty ends',type:'date'},{key:'compatibility',label:'Confirmed compatible parts',hint:'Record only combinations confirmed by the manufacturer or clinician.'},status(['In use','In repair','Loan','Retired']),note]},
 repairs:{title:'Repairs & support',singular:'case',description:'A clear next step for every patient request.',group:'CARE',columns:['name','patientId','priority','supplierId','due','status'],status:['New','Assessment','Awaiting parts','With supplier','Ready to return','Resolved'],fields:[{key:'name',label:'Issue',required:true},patient,{key:'deviceId',label:'Device',ref:'devices'},{key:'supplierId',label:'Supplier',ref:'suppliers'},{key:'priority',label:'Priority',type:'select',options:['Routine','High','Urgent'],required:true},{key:'due',label:'Response due',type:'date'},{key:'tracking',label:'Tracking reference'},{key:'estimatedCost',label:'Estimated repair cost (£)',type:'number',min:0},{key:'loanDevice',label:'Loan device reference'},status(['New','Assessment','Awaiting parts','With supplier','Ready to return','Resolved']),note]},
 appointments:{title:'Appointments',singular:'appointment',description:'Clinic, home and remote follow-up appointments.',group:'CARE',columns:['name','patientId','start','clinician','location','status'],status:['Requested','Confirmed','Completed','Cancelled'],fields:[{key:'name',label:'Appointment type',type:'select',options:['Hearing assessment','Fitting','Follow-up','Repair collection','Remote support','Care-home visit'],required:true},patient,{key:'clinician',label:'Clinician',required:true},{key:'start',label:'Date and time (UK)',type:'datetime-local',required:true},{key:'duration',label:'Duration (minutes)',type:'select',options:['15','30','45','60','90'],required:true},{key:'location',label:'Location',required:true},status(['Requested','Confirmed','Completed','Cancelled']),note]},
 'care-homes':{title:'Care homes',singular:'care home',description:'Resident support, staff contacts and daily checks.',group:'CARE',columns:['name','contact','email','visitDate','status'],fields:[{key:'name',label:'Care-home name',required:true},{key:'contact',label:'Lead contact',required:true},{key:'email',label:'Email',type:'email'},{key:'phone',label:'Telephone'},{key:'address',label:'Address'},{key:'visitDate',label:'Next visit',type:'date'},status(['Active','Onboarding','Paused']),note]},
 checks:{title:'Care checks',singular:'care check',description:'Record routine checks and escalate issues to the clinic.',group:'CARE',columns:['patientId','checkedAt','name','status'],fields:[patient,{key:'name',label:'Check',type:'select',options:['Daily device check','Charging check','Supplies check','Comfort check'],required:true},{key:'checkedAt',label:'Checked on',type:'date',required:true},status(['Working well','Support needed','Device missing']),note]},
 outcomes:{title:'Patient feedback',singular:'feedback',description:'Track patient-reported experience and service quality.',group:'CARE',columns:['patientId','date','hearingScore','satisfaction','name'],fields:[patient,{key:'name',label:'Listening goal',required:true},{key:'date',label:'Recorded on',type:'date',required:true},{key:'hearingScore',label:'Self-reported listening ease (0–10)',type:'number',min:0,max:10,required:true},{key:'satisfaction',label:'Service satisfaction (1–5)',type:'number',min:1,max:5,required:true},note]},
 products:{title:'Supplies & inventory',singular:'product',description:'A verified catalogue and a clear view of stock.',group:'SUPPLY CHAIN',columns:['name','sku','supplierId','price','stock','reorder'],fields:[{key:'name',label:'Product name',required:true},{key:'sku',label:'SKU',required:true},{key:'supplierId',label:'Supplier',ref:'suppliers',required:true},{key:'compatibility',label:'Manufacturer-confirmed compatibility',required:true},{key:'price',label:'Selling price (£)',type:'number',min:0,required:true},{key:'cost',label:'Unit cost (£)',type:'number',min:0,required:true},{key:'stock',label:'Units on hand',type:'number',min:0,required:true},{key:'reorder',label:'Reorder threshold',type:'number',min:0,required:true},note]},
 orders:{title:'Supply orders',singular:'order',description:'From patient request to confirmed delivery.',group:'SUPPLY CHAIN',columns:['name','patientId','productId','quantity','amount','status'],status:['Requested','Confirmed','Dispatched','Delivered','Cancelled'],fields:[{key:'name',label:'Order reference',required:true},patient,{key:'productId',label:'Product',ref:'products',required:true},{key:'quantity',label:'Quantity',type:'number',min:1,max:1000,required:true},{key:'address',label:'Delivery address',required:true},{key:'tracking',label:'Tracking reference'},{key:'repeatDays',label:'Repeat reminder every (days)',type:'number',min:0,max:365,hint:'Creates a reminder only. Each repeat order needs confirmation.'},{key:'nextOrder',label:'Next supply reminder',type:'date'},status(['Requested','Confirmed','Dispatched','Delivered','Cancelled']),note]},
 suppliers:{title:'Supply partners',singular:'supplier',description:'Contacts, repair terms and fulfilment agreements.',group:'SUPPLY CHAIN',columns:['name','service','leadDays','email','status'],fields:[{key:'name',label:'Company name',required:true},{key:'service',label:'Service',type:'select',options:['Consumables','Repairs','Devices','Logistics','Audiology'],required:true},{key:'email',label:'Email',type:'email'},{key:'phone',label:'Telephone'},{key:'leadDays',label:'Agreed turnaround (days)',type:'number',min:0},status(['Active','In discussion','Paused']),note]},
 plans:{title:'Service plans',singular:'plan',description:'Define your patient subscriptions and service allowances.',group:'COMMERCIAL',columns:['name','monthlyPrice','includedCases','repairDiscount','status'],fields:[{key:'name',label:'Plan name',required:true},{key:'monthlyPrice',label:'Monthly price (£)',type:'number',min:0,required:true},{key:'includedCases',label:'Included support cases per month',type:'number',min:0,required:true},{key:'repairDiscount',label:'Repair discount (%)',type:'number',min:0,max:100},{key:'benefits',label:'Included services',type:'textarea',required:true},status(['Active','Draft','Retired'])]},
 invoices:{title:'Billing & invoices',singular:'invoice',description:'Issue invoices, record payments and reconcile balances.',group:'COMMERCIAL',columns:['name','patientId','amount','due','status'],status:['Draft','Issued','Paid','Void'],fields:[{key:'name',label:'Invoice reference',required:true},patient,{key:'description',label:'Services / goods',type:'textarea',required:true},{key:'amount',label:'Total payable (£)',type:'number',min:0.01,required:true},{key:'due',label:'Due date',type:'date',required:true},{key:'paymentReference',label:'Payment reference',hint:'For manually recorded payments.'},status(['Draft','Issued','Paid','Void'])]},
 leads:{title:'Growth pipeline',singular:'opportunity',description:'Build your clinic and care-home partner network.',group:'COMMERCIAL',columns:['name','contact','value','nextAction','status'],status:['New','Qualified','Pilot proposed','Pilot active','Won','Lost'],fields:[{key:'name',label:'Organisation',required:true},{key:'contact',label:'Contact name',required:true},{key:'email',label:'Email',type:'email'},{key:'value',label:'Potential annual contract (£)',type:'number',min:0,required:true},{key:'nextAction',label:'Next action',required:true},{key:'due',label:'Follow-up date',type:'date'},status(['New','Qualified','Pilot proposed','Pilot active','Won','Lost']),note]},
 messages:{title:'Messages',singular:'message',description:'Secure updates shared with the patient and authorised carers.',group:'WORKSPACE',columns:['name','patientId','category','createdAt'],fields:[patient,{key:'name',label:'Subject',required:true},{key:'body',label:'Message',type:'textarea',required:true},{key:'category',label:'Category',type:'select',options:['Care update','Repair update','Supply question','Appointment','General'],required:true}]},
 tasks:{title:'Tasks',singular:'task',description:'Keep ownership and next actions clear.',group:'WORKSPACE',columns:['name','assignee','patientId','due','status'],fields:[{key:'name',label:'Task',required:true},{key:'assignee',label:'Assigned to',required:true},{...patient,required:false},{key:'due',label:'Due date',type:'date',required:true},status(['To do','In progress','Done']),note]},
 consents:{title:'Consent & access',singular:'consent',description:'Document permission and manage authorised carer access.',group:'WORKSPACE',columns:['patientId','name','email','date','status'],fields:[patient,{key:'name',label:'Permission',type:'select',options:['Carer access','Care coordination','Service communications'],required:true},{key:'email',label:'Authorised person email',type:'email',hint:'Required for carer access; must match their signed-in account.'},{key:'date',label:'Recorded on',type:'date',required:true},{key:'basis',label:'Permission evidence / reference',required:true},status(['Granted','Withdrawn'])]},
};
export const roles=['admin','clinician','coordinator','supplier','patient','carer'] as const;
export type Role=typeof roles[number];
export function labelOf(r:CareRecord){return String(r.data.name||r.id.slice(0,8))}
export function money(n:unknown){return new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:2}).format(Number(n)||0)}
export const closedStatuses=['Resolved','Delivered','Cancelled','Completed','Done','Void','Lost','Retired','Inactive'];
export const staffRoles=['admin','clinician','coordinator'];
export const patientKinds=['patients','devices','repairs','appointments','orders','messages','outcomes','consents','documents','invoices'];
export const supplierKinds=['repairs','orders'];
