import type { Data } from './model';
export function demoRecords(){
 const date=(days:number)=>{const d=new Date();d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)};
 const rows:{id:string;kind:string;data:Data}[]=[];
 const add=(kind:string,id:string,data:Data)=>rows.push({kind,id,data});
 add('plans','plan-1',{name:'Essential',monthlyPrice:19,includedCases:2,repairDiscount:0,benefits:'Care coordination, service reminders, device passport and secure messages.',status:'Active'});
 add('plans','plan-2',{name:'Complete',monthlyPrice:39,includedCases:5,repairDiscount:10,benefits:'Essential services, priority coordination and supply reminders. Clinical visits charged separately.',status:'Active'});
 add('plans','plan-3',{name:'Assisted',monthlyPrice:69,includedCases:10,repairDiscount:15,benefits:'Complete services, authorised carer access and care-home coordination. Clinical visits charged separately.',status:'Active'});
 add('care-homes','home-1',{name:'Willow Court',contact:'Alex Parker',email:'willow@example.com',address:'Demonstration address',visitDate:date(3),status:'Active'});
 add('care-homes','home-2',{name:'Oakfield House',contact:'Jamie Lane',email:'oakfield@example.com',address:'Demonstration address',visitDate:date(6),status:'Active'});
 const names=['Margaret Ellis','Robert Bennett','Patricia Green','David Wilson','Susan Clarke','Michael Foster','Elizabeth Reed','James Walker','Anne Morgan','Peter Hughes','Diana Webb','Thomas Brooks'];
 names.forEach((name,i)=>{add('patients',`p-${i}`,{name,email:`patient${i+1}@example.com`,phone:'',postcode:'',funding:i===3?'NHS':'Private',planId:i===3?'':`plan-${i%3+1}`,careHomeId:i%4===0?'home-1':i%5===0?'home-2':'',communication:i%4===0?'Carer':'Email',nextReview:date(i-2),status:i<3?'Review due':'Active',notes:'Fictional demonstration record.'});add('devices',`d-${i}`,{name:i%2?'Auris R4':'Clarity S2',manufacturer:'Example manufacturer',patientId:`p-${i}`,serial:`DEMO-${1001+i}`,side:'Pair',fitted:date(-180),warranty:date(i===0?14:400),compatibility:'Example catalogue only — verify before use.',status:i<4?'In repair':'In use'});});
 add('suppliers','s-1',{name:'Meridian Hearing Supply',service:'Consumables',email:'supplies@example.com',leadDays:3,status:'Active',notes:'Fictional demonstration partner.'});
 add('suppliers','s-2',{name:'Precision Repair Centre',service:'Repairs',email:'repairs@example.com',leadDays:5,status:'Active',notes:'Fictional demonstration partner.'});
 ['Wax filter pack','Open dome pack','Size 312 battery pack','Drying capsules','Cleaning kit','Replacement tubing'].forEach((name,i)=>add('products',`prod-${i}`,{name,sku:`HR-${100+i}`,supplierId:'s-1',compatibility:'Demonstration part — clinician to verify model compatibility',price:[8,12,5.5,9,14,6][i],cost:[3,4,2,3.5,5,2][i],stock:[6,24,48,3,18,32][i],reorder:10}));
 [ ['Intermittent sound in left aid','High','Awaiting parts'],['Charging dock not responding','Routine','With supplier'],['Replacement tube required','Routine','Ready to return'],['Device stopped working','Urgent','New'],['Help pairing with telephone','Routine','Assessment'],['Comfort review requested','High','Assessment'] ].forEach((r,i)=>add('repairs',`r-${i}`,{name:r[0],priority:r[1],status:r[2],patientId:`p-${i}`,deviceId:`d-${i}`,supplierId:'s-2',due:date(i-1),estimatedCost:[45,60,18,75,0,0][i],notes:'Sample service request.'}));
 [0,1,2,3].forEach(i=>add('appointments',`a-${i}`,{name:['Follow-up','Fitting','Remote support','Care-home visit'][i],patientId:`p-${i+2}`,clinician:i%2?'Emma Taylor':'Daniel Lee',start:`${date(i===3?1:0)}T${['09:30','11:00','14:00','10:00'][i]}`,duration:'30',location:i===2?'Remote appointment':'Northside clinic',status:'Confirmed'}));
 [0,1,2,3].forEach(i=>add('orders',`o-${i}`,{name:`ORD-${2401+i}`,patientId:`p-${i}`,productId:`prod-${i}`,supplierId:'s-1',quantity:2,amount:[16,24,11,18][i],unitPrice:[8,12,5.5,9][i],unitCost:[3,4,2,3.5][i],address:'Demonstration delivery address',repeatDays:90,nextOrder:date(20+i),status:['Requested','Dispatched','Delivered','Confirmed'][i],stockReserved:i!==0}));
 [0,1,2,3,4,5].forEach(i=>add('invoices',`i-${i}`,{name:`INV-${1001+i}`,patientId:`p-${i}`,description:'Monthly coordination service — demonstration',amount:[39,69,19,45,39,69][i],due:date(i-3),status:i<2?'Paid':i===5?'Draft':'Issued',paymentReference:i<2?'DEMO-PAYMENT':''}));
 ['Westbrook Audiology','Horizon Care Group','Riverside Hearing','Park Lane Clinic'].forEach((name,i)=>add('leads',`l-${i}`,{name,contact:['Alex Morgan','Sam Taylor','Jo Davis','Charlie Reed'][i],email:`partner${i}@example.com`,value:[7200,18000,4800,9600][i],nextAction:['Arrange discovery call','Share pilot proposal','Review pilot outcomes','Confirm onboarding'][i],due:date(i+1),status:['Qualified','Pilot proposed','Pilot active','Won'][i]}));
 [0,1,2].forEach(i=>add('tasks',`t-${i}`,{name:['Confirm replacement-part compatibility','Arrange return delivery','Follow up review appointment'][i],assignee:'Care coordination team',patientId:`p-${i}`,due:date(i),status:i===1?'In progress':'To do'}));
 [0,1,2,3,4,5].forEach(i=>add('outcomes',`f-${i}`,{patientId:`p-${i}`,name:'Enjoy conversation with family',date:date(-i*3),hearingScore:[7,8,6,9,7,8][i],satisfaction:[5,4,5,4,5,4][i]}));
 add('messages','msg-1',{patientId:'p-0',name:'Your repair is progressing',body:'We are checking the replacement part with the supplier. Your coordinator will update you when a return date is confirmed.',category:'Repair update'});
 add('checks','check-1',{patientId:'p-0',name:'Daily device check',checkedAt:date(0),status:'Support needed',notes:'Repair already open.'});
 add('consents','consent-1',{patientId:'p-0',name:'Carer access',email:'carer@example.com',date:date(-10),basis:'Fictional consent example',status:'Granted'});
 return rows;
}
