import { env } from './runtime-env';
import { cookies } from 'next/headers';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { modules, roles, staffRoles, patientKinds, supplierKinds, type CareRecord, type Data, type Role } from './model';
import { demoRecords } from './seed';
import { z } from 'zod';
export class AppError extends Error {constructor(public status:number,message:string){super(message)}}
export function database(){if(!env.DB)throw new AppError(503,'The record service is unavailable. Please try again.');return env.DB;}
export type Context={workspace:any;user:{userId:string;email:string;displayName:string}|null;role:Role;patientIds:string[];supplierId:string;cookie?:string;workspaces:any[];actor:string};
export function rawRecord(r:any):CareRecord {return {...r,data:JSON.parse(r.data)}}
export function response(data:unknown,c?:Context,status=200){const h=new Headers({'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});if(c?.cookie)h.set('Set-Cookie',c.cookie);return new Response(JSON.stringify(data),{status,headers:h})}
export function fail(e:unknown,c?:Context){if(e instanceof AppError)return response({error:e.message},c,e.status);console.error('Hearing request failed',e instanceof Error?e.message:'Unknown error');return response({error:'Unable to save or load this request. Your changes have not been confirmed. Please retry.'},c,503)}
export function checkOrigin(req:Request){const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin)throw new AppError(403,'Please submit this action from the app.');}
async function hash(s:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(x=>x.toString(16).padStart(2,'0')).join('')}
export async function context(req:Request):Promise<Context>{
 const db=database(),user=await getChatGPTUser();let token=(await cookies()).get('hearing_demo')?.value, cookie:string|undefined;
 if(!token||!/^[a-f0-9]{64}$/.test(token)){token=[...crypto.getRandomValues(new Uint8Array(32))].map(x=>x.toString(16).padStart(2,'0')).join('');cookie=`hearing_demo=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${new URL(req.url).protocol==='https:'?'; Secure':''}`;}
 const owner=user?.userId||`visitor:${token}`;const demoId=`demo_${await hash(owner)}`;
 let demo=await db.prepare('SELECT * FROM workspaces WHERE id=?').bind(demoId).first();
 if(!demo){const now=new Date().toISOString();const seed=demoRecords();const prefix=demoId+':';const statements=[db.prepare('INSERT OR IGNORE INTO workspaces(id,owner,name,demo,created_at) VALUES(?,?,?,?,?)').bind(demoId,owner,'Northside Hearing',1,now),...seed.map(r=>{const data:Data={...r.data};for(const f of modules[r.kind].fields)if(f.ref&&data[f.key])data[f.key]=prefix+data[f.key];return db.prepare('INSERT OR IGNORE INTO records(id,workspace_id,kind,patient_id,supplier_id,data,revision,created_at,updated_at,archived) VALUES(?,?,?,?,?,?,1,?,?,0)').bind(prefix+r.id,demoId,r.kind,data.patientId||null,data.supplierId||null,JSON.stringify(data),now,now)})];await db.batch(statements);demo=await db.prepare('SELECT * FROM workspaces WHERE id=?').bind(demoId).first();}
 let workspaces:any[]=[demo];if(user){const result=await db.prepare('SELECT DISTINCT w.* FROM workspaces w LEFT JOIN members m ON m.workspace_id=w.id AND m.active=1 WHERE (w.owner=? OR m.email=?) AND w.demo=0 ORDER BY w.created_at').bind(user.userId,user.email.toLowerCase()).all();workspaces=[demo,...result.results];}
 const selected=new URL(req.url).searchParams.get('workspace')||demoId;const workspace=workspaces.find(w=>w.id===selected);if(!workspace)throw new AppError(403,'You do not have access to this workspace.');
 let role:Role='admin',patientIds:string[]=[],supplierId='';if(workspace.owner!==owner){if(!user)throw new AppError(401,'Sign in to continue.');const m:any=await db.prepare('SELECT * FROM members WHERE workspace_id=? AND email=? AND active=1').bind(selected,user.email.toLowerCase()).first();if(!m)throw new AppError(403,'Workspace access has been removed.');role=m.role;patientIds=JSON.parse(m.patient_ids);supplierId=m.supplier_id||'';if(role==='carer'){const cons=await db.prepare("SELECT patient_id FROM records WHERE workspace_id=? AND kind='consents' AND archived=0 AND json_extract(data,'$.status')='Granted' AND lower(json_extract(data,'$.email'))=? AND json_extract(data,'$.name')='Carer access'").bind(selected,user.email.toLowerCase()).all();const allowed=new Set(cons.results.map((r:any)=>r.patient_id));patientIds=patientIds.filter(id=>allowed.has(id));}}
 return {workspace,user,role,patientIds,supplierId,cookie,workspaces,actor:user?.email||'Demo visitor'};
}
export function canRead(r:CareRecord,c:Context){if(staffRoles.includes(c.role))return true;if(c.role==='supplier')return supplierKinds.includes(r.kind)&&r.supplier_id===c.supplierId;return patientKinds.includes(r.kind)&&(r.kind==='patients'?c.patientIds.includes(r.id):c.patientIds.includes(String(r.patient_id)));}
export function projectRecord(r:CareRecord,c:Context){if(staffRoles.includes(c.role))return r;const d={...r.data};delete d.notes;delete d.cost;delete d.unitCost;delete d.estimatedCost;delete d.internalNotes;if(c.role==='supplier'){const allow=r.kind==='repairs'?['name','status','priority','due','tracking']:['name','status','quantity','address','tracking'];return {...r,patient_id:undefined,data:Object.fromEntries(Object.entries(d).filter(([k])=>allow.includes(k)))};}return {...r,data:d}}
export async function allRecords(c:Context){const r=await database().prepare('SELECT * FROM records WHERE workspace_id=? AND archived=0 ORDER BY created_at DESC').bind(c.workspace.id).all();return r.results.map(rawRecord);}
export async function state(c:Context){const all=await allRecords(c);const members=c.role==='admin'?(await database().prepare('SELECT id,name,email,role,patient_ids,supplier_id,active FROM members WHERE workspace_id=?').bind(c.workspace.id).all()).results:[];const events=staffRoles.includes(c.role)?(await database().prepare('SELECT * FROM audit WHERE workspace_id=? ORDER BY created_at DESC LIMIT 100').bind(c.workspace.id).all()).results:[];return {workspace:c.workspace,workspaces:c.workspaces.map(w=>({id:w.id,name:w.name,demo:w.demo})),user:c.user?{name:c.user.displayName,email:c.user.email}:null,role:c.role,records:all.filter(r=>canRead(r,c)).map(r=>projectRecord(r,c)),members,events,integrations:{payments:!!(env as any).STRIPE_SECRET_KEY,webhooks:!!(env as any).STRIPE_WEBHOOK_SECRET,supplier:'manual',notifications:'in-app',calendar:'ics'}};}
function validate(kind:string,input:unknown):Data{const mod=modules[kind];if(!mod)throw new AppError(400,'Unknown record type.');const shape:Record<string,z.ZodTypeAny>={};for(const f of mod.fields){let v:z.ZodTypeAny;if(f.type==='number'){v=z.coerce.number().finite().min(f.min??0).max(f.max??10000000);if(['stock','quantity','reorder','includedCases','repeatDays'].includes(f.key))v=(v as z.ZodNumber).int();}else if(f.type==='boolean')v=z.boolean();else{v=z.string().trim().max(f.type==='textarea'?6000:500);if(f.required)v=(v as z.ZodString).min(1,`${f.label} is required`);if(f.options)v=z.enum(f.options as [string,...string[]]);if(f.type==='email')v=z.union([z.literal(''),z.string().email().max(250)]);if(f.type==='date')v=z.union([z.literal(''),z.string().regex(/^\d{4}-\d{2}-\d{2}$/)]);if(f.type==='datetime-local')v=z.string().regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/);}
 shape[f.key]=f.required?v:v.optional();}const parsed=z.object(shape).strict().safeParse(input);if(!parsed.success)throw new AppError(400,parsed.error.issues.map(e=>`${e.path.join('.')}: ${e.message}`).join('; '));return parsed.data as Data;}
export const auditStatement=(c:Context,id:string,action:string,summary:string)=>database().prepare('INSERT INTO audit(id,workspace_id,record_id,actor,action,summary,created_at) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),c.workspace.id,id,c.actor,action,summary,new Date().toISOString());
export async function writeRecord(c:Context,body:any){
 const {kind,id,revision,archive}=body;const db=database();const staff=staffRoles.includes(c.role);if(!modules[kind])throw new AppError(400,'Unknown record type.');
 const existing:any=id?await db.prepare('SELECT * FROM records WHERE id=? AND workspace_id=? AND archived=0').bind(id,c.workspace.id).first():null;
 if(id&&!existing)throw new AppError(404,'Record not found.');const old:CareRecord|null=existing?rawRecord(existing):null;
 if(old&&(old.kind!==kind||!canRead(old,c)))throw new AppError(403,'This record is outside your access.');
 if(old&&revision!==old.revision)throw new AppError(409,'This record has changed. Refresh and try again.');
 if(['plans','suppliers','products','leads','invoices','consents'].includes(kind)&&!staff)throw new AppError(403,'Your role cannot change this record.');
 if(c.role==='supplier'){if(!old||!['repairs','orders'].includes(kind)||archive)throw new AppError(403,'Suppliers can update assigned work only.');const changed=Object.keys(body.data||{}).filter(k=>body.data[k]!==old.data[k]);if(changed.some(k=>!['status','tracking'].includes(k)))throw new AppError(403,'Only delivery and repair progress may be changed.');}
 if(!staff&&c.role!=='supplier'){if(archive||old||!['repairs','messages','outcomes','appointments'].includes(kind))throw new AppError(403,'Your role cannot perform this action.');if(!c.patientIds.includes(body.data?.patientId))throw new AppError(403,'Select a patient linked to your account.');}
 if(archive){if(!staff)throw new AppError(403,'Staff access required.');if(['orders','invoices','appointments','consents'].includes(kind))throw new AppError(400,'Use the status field to cancel, void or withdraw this record.');const references=await allRecords(c);if(references.some(r=>r.id!==id&&Object.entries(r.data).some(([k,v])=>k.endsWith('Id')&&v===id)))throw new AppError(409,'This record has linked records. Retain it and update its status.');await db.batch([db.prepare('INSERT INTO receipts(id,created_at) VALUES(?,?)').bind(`edit:${id}:${revision}`,new Date().toISOString()),db.prepare('UPDATE records SET archived=1,revision=revision+1 WHERE id=? AND workspace_id=?').bind(id,c.workspace.id),auditStatement(c,id,'archived',`${kind}: ${old?.data.name||id}`)]);return {id};}
 const clean=c.role==='supplier'&&old?{...old.data,...body.data}:{...body.data};for(const k of ['amount','unitPrice','unitCost','stockReserved'])if(kind==='orders')delete clean[k];delete clean.createdAt;
 const data=validate(kind,clean);if(c.role==='supplier'&&old)Object.assign(data,old.data,{status:clean.status,tracking:clean.tracking});
 if(!staff&&c.role!=='supplier'){if(kind==='repairs')Object.assign(data,{status:'New',priority:'Routine',supplierId:'',estimatedCost:0});if(kind==='appointments')data.status='Requested';}
 for(const f of modules[kind].fields.filter(f=>f.ref)){if(data[f.key]){const linked:any=await db.prepare('SELECT * FROM records WHERE id=? AND workspace_id=? AND kind=? AND archived=0').bind(data[f.key],c.workspace.id,f.ref).first();if(!linked)throw new AppError(400,`Choose a valid ${f.label.toLowerCase()}.`);if(f.ref==='devices'&&linked.patient_id!==data.patientId)throw new AppError(400,'The selected device belongs to another patient.');}}
 if(kind==='consents'&&data.name==='Carer access'&&!data.email)throw new AppError(400,'A carer email is required.');
 if(kind==='invoices'&&data.status==='Paid'&&!data.paymentReference)throw new AppError(400,'Add the payment reference before recording a manual payment.');
 if(kind==='invoices'&&old?.data.status==='Paid'&&JSON.stringify(data)!==JSON.stringify(old.data))throw new AppError(409,'Paid invoices are retained unchanged. Create a separate adjustment invoice.');
 const recordId=id||crypto.randomUUID(),now=new Date().toISOString();const ops:D1PreparedStatement[]=[];
 if(old)ops.push(db.prepare('INSERT INTO receipts(id,created_at) VALUES(?,?)').bind(`edit:${id}:${revision}`,now));
 if(kind==='orders'){
  const product=rawRecord(await db.prepare('SELECT * FROM records WHERE id=? AND workspace_id=?').bind(data.productId,c.workspace.id).first());
  if(old?.data.stockReserved&&(data.productId!==old.data.productId||data.quantity!==old.data.quantity))throw new AppError(409,'Cancel this order before changing reserved items.');
  if(old?.data.status==='Cancelled'&&data.status!=='Cancelled')throw new AppError(409,'Create a new order to replace a cancelled order.');
  if(old?.data.status==='Delivered'&&data.status!=='Delivered')throw new AppError(409,'A delivered order is final. Record any return separately.');
  if(old?.data.stockReserved&&data.status==='Requested')throw new AppError(409,'Cancel a reserved order before creating a new request.');
  const reserve=['Confirmed','Dispatched','Delivered'].includes(String(data.status));const was=!!old?.data.stockReserved;
  data.unitPrice=old?.data.unitPrice??product.data.price;data.unitCost=old?.data.unitCost??product.data.cost;data.amount=Math.round(Number(data.unitPrice)*Number(data.quantity)*100)/100;data.supplierId=product.data.supplierId;data.stockReserved=reserve;
  if(reserve!==was){const delta=reserve?-Number(data.quantity):Number(data.quantity);ops.push(db.prepare("UPDATE records SET data=json_set(data,'$.stock',CAST(json_extract(data,'$.stock') AS INTEGER)+?),revision=revision+1,updated_at=? WHERE id=? AND workspace_id=?").bind(delta,now,data.productId,c.workspace.id));}
 }
 if(kind==='appointments'){
  const duration=Number(data.duration);const start=Date.parse(String(data.start)+'Z');if(!Number.isFinite(start)||new Date(start).getUTCMinutes()%15!==0)throw new AppError(400,'Choose a valid start time in 15-minute intervals.');
  if(old)ops.push(db.prepare('DELETE FROM slots WHERE record_id=? AND workspace_id=?').bind(recordId,c.workspace.id));
  if(data.status==='Confirmed')for(let m=0;m<duration;m+=15)ops.push(db.prepare('INSERT INTO slots(id,record_id,workspace_id) VALUES(?,?,?)').bind(`${c.workspace.id}:${String(data.clinician).trim().toLowerCase()}:${start+m*60000}`,recordId,c.workspace.id));
 }
 if(old)ops.push(db.prepare('UPDATE records SET data=?,patient_id=?,supplier_id=?,revision=revision+1,updated_at=? WHERE id=? AND workspace_id=?').bind(JSON.stringify(data),data.patientId||null,data.supplierId||null,now,recordId,c.workspace.id));
 else ops.push(db.prepare('INSERT INTO records(id,workspace_id,kind,patient_id,supplier_id,data,revision,created_at,updated_at,archived) VALUES(?,?,?,?,?,?,1,?,?,0)').bind(recordId,c.workspace.id,kind,data.patientId||null,data.supplierId||null,JSON.stringify(data),now,now));
 ops.push(auditStatement(c,recordId,old?'updated':'created',`${modules[kind].singular}: ${data.name||recordId.slice(0,8)}`));
 try{await db.batch(ops)}catch(e){const msg=String(e);if(/UNIQUE|CHECK|constraint/i.test(msg))throw new AppError(409,kind==='orders'?'There is not enough stock, or this order has changed. Refresh before retrying.':kind==='appointments'?'That time is already booked, or this appointment has changed. Choose another slot.':'This record has changed. Refresh before retrying.');throw e;}
 return {id:recordId};
}
export async function addMember(c:Context,b:any){if(c.role!=='admin')throw new AppError(403,'Administrator access required.');const v=z.object({id:z.string().optional(),name:z.string().min(1).max(120),email:z.string().email(),role:z.enum(roles),patientIds:z.array(z.string()).max(100).default([]),supplierId:z.string().default(''),active:z.boolean().default(true)}).strict().safeParse(b);if(!v.success)throw new AppError(400,'Complete the name, valid email and role.');const d=v.data;if(['patient','carer'].includes(d.role)&&!d.patientIds.length)throw new AppError(400,'Link at least one patient.');if(d.role==='supplier'&&!d.supplierId)throw new AppError(400,'Link a supply partner.');const all=await allRecords(c);if(d.patientIds.some(id=>!all.some(r=>r.id===id&&r.kind==='patients')))throw new AppError(400,'Invalid patient link.');if(d.supplierId&&!all.some(r=>r.id===d.supplierId&&r.kind==='suppliers'))throw new AppError(400,'Invalid supplier.');const id=d.id||crypto.randomUUID();if(d.id){const m=await database().prepare('SELECT id FROM members WHERE id=? AND workspace_id=?').bind(id,c.workspace.id).first();if(!m)throw new AppError(404,'Member not found.');}
 await database().batch([database().prepare('INSERT INTO members(id,workspace_id,email,name,role,patient_ids,supplier_id,active) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(workspace_id,email) DO UPDATE SET name=excluded.name,role=excluded.role,patient_ids=excluded.patient_ids,supplier_id=excluded.supplier_id,active=excluded.active').bind(id,c.workspace.id,d.email.toLowerCase(),d.name,d.role,JSON.stringify(d.patientIds),d.supplierId||null,d.active?1:0),auditStatement(c,id,'access updated',`${d.name} · ${d.role} · ${d.active?'active':'revoked'}`)]);return {id};}
